### ISSUE TITLE
几个疑问

### ISSUE THREAD

**Issue by vihuela** [xudjx/webprogress#1]
①我理解的aidl，只看目的的话，就是获取其它进程的代理引用，和平常接口回调一样，只是实现用了aidl
②假设A进程是mainActivity，B进程是独立进程的webView，那aidl的绑定服务应该处于A进程使用aidl绑定服务获取B进程的接口引用，然后A进程传参数给B进程，但是demo中，好像绑定和传参数都发生在B进程啊？？

**Comment by xudjx** [comment]
1的理解是没错的；对于第二点，A进程是主进程，是服务的提供者，B进程是服务的调用者，B进程通过AIDL方式去获取A进程的服务，所以你的理解刚好相反

**Comment by 50kg** [comment]
@xudjx 和楼主理解一样，看demo有点晕。
1：问一下A主进程怎么拿到B进程web的回调
2：如果做刷新、返回，这些逻辑UI是放在WebActivity里还是CommonWebFragment里呢？

**Comment by xudjx** [comment]
> @xudjx 和楼主理解一样，看demo有点晕。
> 1：问一下A主进程怎么拿到B进程web的回调
> 2：如果做刷新、返回，这些逻辑UI是放在WebActivity里还是CommonWebFragment里呢？

A进程是没法直接拿到B进程Web的回调的，你需要自己写Web的delegate，然后持有delegate，通过进程通信来桥接；同样的，刷新等各种操作也可以通过delegate来做

**Comment by xudjx** [comment]
> @xudjx 和楼主理解一样，看demo有点晕。
> 1：问一下A主进程怎么拿到B进程web的回调
> 2：如果做刷新、返回，这些逻辑UI是放在WebActivity里还是CommonWebFragment里呢？

A进程是没法直接拿到B进程Web的回调的，你需要自己写Web的delegate，然后持有delegate，通过进程通信来桥接；同样的，刷新等各种操作也可以通过delegate来做
